import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Domine } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import dynamic from "next/dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const domine = Domine({
  subsets: ["latin"],
  variable: "--font-domine",
});

const Navbar = dynamic(() => import("@/components/Navbar"), { ssr: true });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${domine.variable} font-domine antialiased bg-white`}
      >
        <Navbar />
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
